Update Makefile

diff --git a/trunk/tools/lzma/Makefile b/trunk/tools/lzma/Makefile
--- a/trunk/tools/lzma/Makefile
+++ b/trunk/tools/lzma/Makefile
@@ -1,7 +1,16 @@
 SRC_NAME=lzma-4.65
 
+# 检查 HOST_NCPU 是否定义，如果没有定义，默认为 1
+ifndef HOST_NCPU
+  HOST_NCPU=1
+endif
+
 all:
-	make -j$(HOST_NCPU) -C $(SRC_NAME)/CPP/7zip/Compress/LZMA_Alone -f makefile.gcc ;\
+	@if [ ! -d "$(SRC_NAME)/CPP/7zip/Compress/LZMA_Alone" ]; then \
+		echo "Source directory $(SRC_NAME)/CPP/7zip/Compress/LZMA_Alone not found!"; \
+		exit 1; \
+	fi
+	make -j$(HOST_NCPU) -C $(SRC_NAME)/CPP/7zip/Compress/LZMA_Alone -f makefile.gcc || { echo "Build failed"; exit 1; }
 	cp $(SRC_NAME)/CPP/7zip/Compress/LZMA_Alone/lzma ./lzma
 
 clean:
